Feat/joeywang/network
Byzanteam/jet-programmable-rust-binding pull request #11
Opened 2022-11-28 04:41 UTC by joeywang321

2022-11-28 06:33 UTC, fahchen requested changes
1. 重做 commit
2. 代码格式有问题，用一下 `cargo fmt`

2022-11-30 02:45 UTC, fahchen commented
rebase 一下

2022-11-30 02:45 UTC, fahchen requested changes
rebase 一下

2022-11-30 06:03 UTC, fahchen requested changes

2022-11-30 06:03 UTC, fahchen commented on src/hostcalls/mod.rs
> +    pub fn hostcall_request_inputs(
用之前的名字

2022-11-30 06:48 UTC, fahchen requested changes

2022-11-30 06:48 UTC, fahchen commented on src/hostcalls/mod.rs
> +    pub fn hostcall_networking_request(
加个注释，参数和返回值分别是指什么

2022-11-30 06:56 UTC, joeywang321 commented on src/hostcalls/mod.rs
> +    pub fn hostcall_networking_request(
ok

2022-11-30 07:22 UTC, fahchen requested changes

2022-11-30 07:22 UTC, fahchen commented on src/hostcalls/mod.rs
> +    // inputs_ptr is requestdata ptr, inputs_len is requestdata length, new_ptr is responsedata ptr, return usize is responsedata length
参考下这个链接重新写下文档：https://doc.rust-lang.org/rust-by-example/meta/doc.html

2022-11-30 07:22 UTC, fahchen commented on src/hostcalls/mod.rs
> +    // inputs_ptr is requestdata ptr, inputs_len is requestdata length, new_ptr is responsedata ptr, return usize is responsedata length
requestdata -> request_data

2022-11-30 07:27 UTC, joeywang321 commented on src/hostcalls/mod.rs
> +    // inputs_ptr is requestdata ptr, inputs_len is requestdata length, new_ptr is responsedata ptr, return usize is responsedata length
师傅，看你发的链接，是要做导出文档吗？

2022-11-30 07:40 UTC, fahchen commented on src/hostcalls/mod.rs
> +    // inputs_ptr is requestdata ptr, inputs_len is requestdata length, new_ptr is responsedata ptr, return usize is responsedata length
不是，是按照规范写文档哈

2022-11-30 07:45 UTC, joeywang321 commented on src/hostcalls/mod.rs
> +    // inputs_ptr is requestdata ptr, inputs_len is requestdata length, new_ptr is responsedata ptr, return usize is responsedata length
<img width="1397" alt="截屏2022-11-30 15 43 56" src="https://user-images.githubusercontent.com/91400014/204736883-57837d5c-d332-4471-a9d1-ab9b8f46912c.png">

这样写怎么样，这个是可以导出的文档

2022-11-30 08:08 UTC, fahchen requested changes

2022-11-30 08:08 UTC, fahchen commented on src/hostcalls/mod.rs
> +    /// * `inputs_ptr` - Request_data Pointer to data
```suggestion
    /// * `inputs_ptr` - RequestData Pointer to data
```

2022-11-30 08:31 UTC, fahchen requested changes

2022-11-30 08:31 UTC, fahchen commented on src/hostcalls/mod.rs
> +    /// * `usize` - ResponseData Length of data
这个不是 argument 哈

2022-11-30 08:40 UTC, joeywang321 commented on src/hostcalls/mod.rs
> +    /// * `usize` - ResponseData Length of data
是说unsize,不用写在上面吗？

2022-11-30 08:46 UTC, fahchen commented on src/hostcalls/mod.rs
> +    /// * `usize` - ResponseData Length of data
这个不应该写入 argument 里面

2022-11-30 09:39 UTC, fahchen requested changes

2022-11-30 09:39 UTC, fahchen commented on src/hostcalls/mod.rs
> +    /// Parameter dan nilai balik untuk permintaan jaringan
这段话是啥意思啊？

2022-11-30 09:39 UTC, fahchen commented on src/hostcalls/mod.rs
> +    /// ```
返回值的注释呢？

2022-11-30 11:19 UTC, fahchen requested changes

2022-11-30 11:19 UTC, fahchen commented on src/hostcalls/mod.rs
> +    /// responsedata = unsafe {
response_data

2022-11-30 11:19 UTC, fahchen commented on src/hostcalls/mod.rs
> +    ///     let len = hostcall_request_inputs(data.as_ptr(), data.len(), responsedata.as_ptr());
function 名字不对

2022-12-01 02:30 UTC, fahchen requested changes

2022-12-01 02:30 UTC, fahchen commented on src/hostcalls/mod.rs
> +    ///     let slice = slice::from_raw_parts(data_string.as_ptr(), len);
认真检查注释里面的代码
```suggestion
    ///     let slice = slice::from_raw_parts(response_data.as_ptr(), len);
```

2022-12-01 03:43 UTC, closed without merging