Fix/joeywang/networking
Byzanteam/jet-programmable-rust-binding pull request #18
Opened 2022-12-14 10:15 UTC by joeywang321

elixir 调用__wasm_malloc后将长度和指针写入到结构体，然后直接在函数里面读取数据进行处理

2022-12-15 01:32 UTC, fahchen requested changes

2022-12-15 01:32 UTC, fahchen commented on src/networking.rs
> +    pub fn new(response_ptr: usize, response_len: usize) -> Self {
```suggestion
    pub fn new() -> Self {
```
这里不要参数吧，直接生成一个ref,反正ptr和len我们在这里没有用

2022-12-15 01:32 UTC, fahchen commented on src/networking.rs
> +    let response_ref = serde_json::to_string(&ResponseRef::new(0, 0)).unwrap();
这里有一点不是特别对，这里我们alloc的是一个长度为ptr加 len的内存，你现在
alloc的是一个JSON字符的长度

2022-12-22 03:00 UTC, fahchen commented on src/networking.rs
> +            &response_len as *const u64,
`response_ptr` 和 `response_len` 这两个应该是 stack 上的数据吧，所以这里拿到的指针指向的是 memory（WASM）的吗？

2022-12-22 06:01 UTC, joeywang321 commented on src/networking.rs
> +            &response_len as *const u64,
嗯嗯，将引用转化为指针，指向栈上的数据

2022-12-22 06:39 UTC, fahchen commented on src/networking.rs
> +            &response_len as *const u64,
这种操作不太好，还是改成操作memory

2022-12-23 03:25 UTC, fahchen requested changes

2022-12-23 03:25 UTC, fahchen commented on src/networking.rs
> +        let response_len = u64::from_str_radix(&response_ref[64..128], 2).unwrap();
把这几步抽象成一个 function

2022-12-23 03:25 UTC, fahchen commented on src/networking.rs
> +        let response_ref = str::from_utf8(response_ref_slice).unwrap();
这里拿到的应该是 bytes，不是 str

2022-12-23 03:25 UTC, fahchen commented on src/networking.rs
> +        hostcall_networking_request(
你思考下让这个 function 返回 `response.ptr`，response 存储的时候按照 `response.len` + `response` 的方式存储，前面固定 u64 存储 len，用来指明后面的 response 的长度，这样，我们就不需要传 response_ref 给 runtime 那边了

2022-12-23 04:06 UTC, fahchen commented on src/hostcalls/mod.rs
> +    /// * return value type is `*const u8` he represents is `response_ptr`
```suggestion
    /// * the returning value is `*const u8` that represents is `response_ptr`
```

2022-12-23 04:06 UTC, fahchen commented on src/networking.rs
> +        let response_len = u64::from_str_radix(response_ref, 2).unwrap();
你拿到 slice 能不能直接转 u64，或者从 byte 转，不走 string

2022-12-26 09:08 UTC, fahchen requested changes

2022-12-26 09:08 UTC, fahchen commented on src/networking.rs
> +use crate::hostcalls::{hostcall_networking_request_len, hostcall_networking_response_ptr};
这两个 function 的名字调整下
```suggestion
use crate::hostcalls::{hostcall_networking_request, hostcall_networking_retrieve_response};
```

2022-12-27 02:16 UTC, fahchen commented on src/hostcalls/mod.rs
> +    /// * the returning value is `usize` that represents is `response_len`
```suggestion
    /// * Return the length of `response`
```

2022-12-27 02:16 UTC, fahchen commented on src/hostcalls/mod.rs
> +    /// `__wasm_malloc` function Get the ptr of the response, pass it to the following function, so that the outside can get a map to write the data to memory
```suggestion
    /// To allocate memory for the response, you can use the `__wasm_malloc` function. Then, pass a pointer to the allocated memory to the following function, so that the runtime can write the response data to it.
```

2022-12-28 02:59 UTC, fahchen requested changes

2022-12-28 02:59 UTC, fahchen commented on src/scaffolding.rs
>      }
这个改动别提交上来了，你不要用撤销键去撤销修改，用 git 去管理，不要直接 `git add .`，根据需要 add，多使用 `git add . -p`

2022-12-28 02:59 UTC, fahchen commented on src/networking.rs
> +pub type NetworkingBody = Option<String>;
这里用 `Vec<u8>` 才对，body 不一定是 `String` 的

2022-12-28 03:12 UTC, joeywang321 commented on src/networking.rs
> +pub type NetworkingBody = Option<String>;
师傅，我们在把数据读出来的时候使用了from_slice，这个已经将Vec<u8>转化成了string，所以我们是本来就用的vec<u8>,只是在读取的时候已经转化成了str，这样在后面在使用vec<u8>,就会报错

2022-12-28 03:40 UTC, fahchen commented on src/networking.rs
> +pub type NetworkingBody = Option<String>;
这里不太对，str 是 utf-8 的 Vec<u8>，反之不成立的
http://doc.rust-lang.org/1.65.0/alloc/str/fn.from_utf8.html

2022-12-28 03:57 UTC, joeywang321 commented on src/networking.rs
> +pub type NetworkingBody = Option<String>;
<img width="764" alt="截屏2022-12-28 11 50 26" src="https://user-images.githubusercontent.com/91400014/209754605-ae197208-f6eb-4ad8-ab92-03d2a6aef39a.png">
我不知道我理解的对不对，我们利用指针和长度，在内存中读取了二进制的vec<u8>类型的数据，但是我们转化成了str，body可能受影响，因为我们如果使用vec<u8>作为body的类型的话，不论是使用struct还是Value反序列化都会失败，但是String就没有问题，或者要使用其他方法对其进行反序列化

2022-12-28 04:07 UTC, fahchen commented on src/networking.rs
> +pub type NetworkingBody = Option<String>;
这里确实受 JSON 的限制，你加个 NOTE 给 body 注释一下吧

2022-12-28 07:56 UTC, fahchen requested changes
重做下 commits

2022-12-29 03:29 UTC, fahchen requested changes
你现在的 commits 拆分有问题，分成两个
1. 完成 request 的逻辑
2. 引入 hostcall_logger_debug

2022-12-29 07:52 UTC, fahchen requested changes

2022-12-29 07:52 UTC, fahchen commented on src/hostcalls/mod.rs
> +}
少了个空行，执行 `cargo fmt`！

2022-12-29 08:35 UTC, merged